/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVehiclesRouteImport } from './routes/_app.vehicles'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSalesRouteImport } from './routes/_app.sales'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppPricingRouteImport } from './routes/_app.pricing'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppExpensesRouteImport } from './routes/_app.expenses'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppVehiclesIndexRouteImport } from './routes/_app.vehicles.index'
import { Route as AppVehiclesNewRouteImport } from './routes/_app.vehicles.new'
import { Route as AppVehiclesIdRouteImport } from './routes/_app.vehicles.$id'
import { Route as AppVehiclesIdIndexRouteImport } from './routes/_app.vehicles.$id.index'
import { Route as AppVehiclesIdEditRouteImport } from './routes/_app.vehicles.$id.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVehiclesRoute = AppVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPricingRoute = AppPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppVehiclesIndexRoute = AppVehiclesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppVehiclesRoute,
} as any)
const AppVehiclesNewRoute = AppVehiclesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppVehiclesRoute,
} as any)
const AppVehiclesIdRoute = AppVehiclesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppVehiclesRoute,
} as any)
const AppVehiclesIdIndexRoute = AppVehiclesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppVehiclesIdRoute,
} as any)
const AppVehiclesIdEditRoute = AppVehiclesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppVehiclesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AppDashboardRoute
  '/expenses': typeof AppExpensesRoute
  '/notifications': typeof AppNotificationsRoute
  '/pricing': typeof AppPricingRoute
  '/reports': typeof AppReportsRoute
  '/sales': typeof AppSalesRoute
  '/settings': typeof AppSettingsRoute
  '/vehicles': typeof AppVehiclesRouteWithChildren
  '/vehicles/$id': typeof AppVehiclesIdRouteWithChildren
  '/vehicles/new': typeof AppVehiclesNewRoute
  '/vehicles/': typeof AppVehiclesIndexRoute
  '/vehicles/$id/edit': typeof AppVehiclesIdEditRoute
  '/vehicles/$id/': typeof AppVehiclesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AppDashboardRoute
  '/expenses': typeof AppExpensesRoute
  '/notifications': typeof AppNotificationsRoute
  '/pricing': typeof AppPricingRoute
  '/reports': typeof AppReportsRoute
  '/sales': typeof AppSalesRoute
  '/settings': typeof AppSettingsRoute
  '/vehicles/new': typeof AppVehiclesNewRoute
  '/vehicles': typeof AppVehiclesIndexRoute
  '/vehicles/$id/edit': typeof AppVehiclesIdEditRoute
  '/vehicles/$id': typeof AppVehiclesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/signup': typeof SignupRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/expenses': typeof AppExpensesRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/pricing': typeof AppPricingRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/sales': typeof AppSalesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/vehicles': typeof AppVehiclesRouteWithChildren
  '/_app/vehicles/$id': typeof AppVehiclesIdRouteWithChildren
  '/_app/vehicles/new': typeof AppVehiclesNewRoute
  '/_app/vehicles/': typeof AppVehiclesIndexRoute
  '/_app/vehicles/$id/edit': typeof AppVehiclesIdEditRoute
  '/_app/vehicles/$id/': typeof AppVehiclesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signup'
    | '/dashboard'
    | '/expenses'
    | '/notifications'
    | '/pricing'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/vehicles'
    | '/vehicles/$id'
    | '/vehicles/new'
    | '/vehicles/'
    | '/vehicles/$id/edit'
    | '/vehicles/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signup'
    | '/dashboard'
    | '/expenses'
    | '/notifications'
    | '/pricing'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/vehicles/new'
    | '/vehicles'
    | '/vehicles/$id/edit'
    | '/vehicles/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/signup'
    | '/_app/dashboard'
    | '/_app/expenses'
    | '/_app/notifications'
    | '/_app/pricing'
    | '/_app/reports'
    | '/_app/sales'
    | '/_app/settings'
    | '/_app/vehicles'
    | '/_app/vehicles/$id'
    | '/_app/vehicles/new'
    | '/_app/vehicles/'
    | '/_app/vehicles/$id/edit'
    | '/_app/vehicles/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/vehicles': {
      id: '/_app/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof AppVehiclesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pricing': {
      id: '/_app/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AppPricingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vehicles/': {
      id: '/_app/vehicles/'
      path: '/'
      fullPath: '/vehicles/'
      preLoaderRoute: typeof AppVehiclesIndexRouteImport
      parentRoute: typeof AppVehiclesRoute
    }
    '/_app/vehicles/new': {
      id: '/_app/vehicles/new'
      path: '/new'
      fullPath: '/vehicles/new'
      preLoaderRoute: typeof AppVehiclesNewRouteImport
      parentRoute: typeof AppVehiclesRoute
    }
    '/_app/vehicles/$id': {
      id: '/_app/vehicles/$id'
      path: '/$id'
      fullPath: '/vehicles/$id'
      preLoaderRoute: typeof AppVehiclesIdRouteImport
      parentRoute: typeof AppVehiclesRoute
    }
    '/_app/vehicles/$id/': {
      id: '/_app/vehicles/$id/'
      path: '/'
      fullPath: '/vehicles/$id/'
      preLoaderRoute: typeof AppVehiclesIdIndexRouteImport
      parentRoute: typeof AppVehiclesIdRoute
    }
    '/_app/vehicles/$id/edit': {
      id: '/_app/vehicles/$id/edit'
      path: '/edit'
      fullPath: '/vehicles/$id/edit'
      preLoaderRoute: typeof AppVehiclesIdEditRouteImport
      parentRoute: typeof AppVehiclesIdRoute
    }
  }
}

interface AppVehiclesIdRouteChildren {
  AppVehiclesIdEditRoute: typeof AppVehiclesIdEditRoute
  AppVehiclesIdIndexRoute: typeof AppVehiclesIdIndexRoute
}

const AppVehiclesIdRouteChildren: AppVehiclesIdRouteChildren = {
  AppVehiclesIdEditRoute: AppVehiclesIdEditRoute,
  AppVehiclesIdIndexRoute: AppVehiclesIdIndexRoute,
}

const AppVehiclesIdRouteWithChildren = AppVehiclesIdRoute._addFileChildren(
  AppVehiclesIdRouteChildren,
)

interface AppVehiclesRouteChildren {
  AppVehiclesIdRoute: typeof AppVehiclesIdRouteWithChildren
  AppVehiclesNewRoute: typeof AppVehiclesNewRoute
  AppVehiclesIndexRoute: typeof AppVehiclesIndexRoute
}

const AppVehiclesRouteChildren: AppVehiclesRouteChildren = {
  AppVehiclesIdRoute: AppVehiclesIdRouteWithChildren,
  AppVehiclesNewRoute: AppVehiclesNewRoute,
  AppVehiclesIndexRoute: AppVehiclesIndexRoute,
}

const AppVehiclesRouteWithChildren = AppVehiclesRoute._addFileChildren(
  AppVehiclesRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPricingRoute: typeof AppPricingRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSalesRoute: typeof AppSalesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppVehiclesRoute: typeof AppVehiclesRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPricingRoute: AppPricingRoute,
  AppReportsRoute: AppReportsRoute,
  AppSalesRoute: AppSalesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppVehiclesRoute: AppVehiclesRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
